// This file is auto-generated by scripts/generate_cloud_ops_tests.mjs.
// Do not edit manually.

use hetzner::HetznerClient;
use httpmock::prelude::*;

#[tokio::test]
async fn test_all_generated_cloud_openapi_operations() {
    let server = MockServer::start();
    let client = HetznerClient::new("test-token").with_cloud_base_url(server.base_url());

    // GET /actions (get_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_actions(None, None).await.unwrap();
    mock.assert();

    // GET /actions/{id} (get_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_action(1, None, None).await.unwrap();
    mock.assert();

    // GET /certificates (list_certificates)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/certificates")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_certificates(None, None).await.unwrap();
    mock.assert();

    // POST /certificates (create_certificate)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/certificates")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_certificate(None, None).await.unwrap();
    mock.assert();

    // GET /certificates/actions (list_certificates_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/certificates/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_certificates_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /certificates/actions/{id} (get_certificates_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/certificates/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_certificates_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /certificates/{id} (get_certificate)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/certificates/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_certificate(1, None, None).await.unwrap();
    mock.assert();

    // PUT /certificates/{id} (update_certificate)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/certificates/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_certificate(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // DELETE /certificates/{id} (delete_certificate)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/certificates/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_certificate(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /certificates/{id}/actions (list_certificate_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/certificates/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_certificate_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /certificates/{id}/actions/retry (retry_certificate)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/certificates/1/actions/retry")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .retry_certificate(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /certificates/{id}/actions/{action_id} (get_certificate_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/certificates/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_certificate_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /datacenters (list_datacenters)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/datacenters")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_datacenters(None, None).await.unwrap();
    mock.assert();

    // GET /datacenters/{id} (get_datacenter)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/datacenters/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_datacenter(1, None, None).await.unwrap();
    mock.assert();

    // GET /firewalls (list_firewalls)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/firewalls")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_firewalls(None, None).await.unwrap();
    mock.assert();

    // POST /firewalls (create_firewall)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/firewalls")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_firewall(None, None).await.unwrap();
    mock.assert();

    // GET /firewalls/actions (list_firewalls_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/firewalls/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_firewalls_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /firewalls/actions/{id} (get_firewalls_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/firewalls/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_firewalls_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /firewalls/{id} (get_firewall)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/firewalls/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_firewall(1, None, None).await.unwrap();
    mock.assert();

    // PUT /firewalls/{id} (update_firewall)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/firewalls/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_firewall(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /firewalls/{id} (delete_firewall)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/firewalls/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_firewall(1, None, None).await.unwrap();
    mock.assert();

    // GET /firewalls/{id}/actions (list_firewall_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/firewalls/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_firewall_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /firewalls/{id}/actions/apply_to_resources (apply_firewall_to_resources)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/firewalls/1/actions/apply_to_resources")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .apply_firewall_to_resources(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /firewalls/{id}/actions/remove_from_resources (remove_firewall_from_resources)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/firewalls/1/actions/remove_from_resources")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .remove_firewall_from_resources(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /firewalls/{id}/actions/set_rules (set_firewall_rules)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/firewalls/1/actions/set_rules")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .set_firewall_rules(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /firewalls/{id}/actions/{action_id} (get_firewall_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/firewalls/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_firewall_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /floating_ips (list_floating_ips)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/floating_ips")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_floating_ips(None, None).await.unwrap();
    mock.assert();

    // POST /floating_ips (create_floating_ip)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/floating_ips")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_floating_ip(None, None).await.unwrap();
    mock.assert();

    // GET /floating_ips/actions (list_floating_ips_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/floating_ips/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_floating_ips_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /floating_ips/actions/{id} (get_floating_ips_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/floating_ips/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_floating_ips_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /floating_ips/{id} (get_floating_ip)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/floating_ips/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_floating_ip(1, None, None).await.unwrap();
    mock.assert();

    // PUT /floating_ips/{id} (update_floating_ip)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/floating_ips/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_floating_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // DELETE /floating_ips/{id} (delete_floating_ip)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/floating_ips/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_floating_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /floating_ips/{id}/actions (list_floating_ip_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/floating_ips/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_floating_ip_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /floating_ips/{id}/actions/assign (assign_floating_ip)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/floating_ips/1/actions/assign")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .assign_floating_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /floating_ips/{id}/actions/change_dns_ptr (change_floating_ip_dns_ptr)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/floating_ips/1/actions/change_dns_ptr")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_floating_ip_dns_ptr(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /floating_ips/{id}/actions/change_protection (change_floating_ip_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/floating_ips/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_floating_ip_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /floating_ips/{id}/actions/unassign (unassign_floating_ip)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/floating_ips/1/actions/unassign")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .unassign_floating_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /floating_ips/{id}/actions/{action_id} (get_floating_ip_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/floating_ips/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_floating_ip_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /images (list_images)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/images")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_images(None, None).await.unwrap();
    mock.assert();

    // GET /images/actions (list_images_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/images/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_images_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /images/actions/{id} (get_images_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/images/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_images_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /images/{id} (get_image)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/images/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_image(1, None, None).await.unwrap();
    mock.assert();

    // PUT /images/{id} (update_image)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/images/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_image(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /images/{id} (delete_image)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/images/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_image(1, None, None).await.unwrap();
    mock.assert();

    // GET /images/{id}/actions (list_image_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/images/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_image_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /images/{id}/actions/change_protection (change_image_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/images/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_image_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /images/{id}/actions/{action_id} (get_image_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/images/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_image_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /isos (list_isos)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/isos")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_isos(None, None).await.unwrap();
    mock.assert();

    // GET /isos/{id} (get_iso)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/isos/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_iso(1, None, None).await.unwrap();
    mock.assert();

    // GET /load_balancer_types (list_load_balancer_types)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancer_types")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_load_balancer_types(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancer_types/{id} (get_load_balancer_type)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancer_types/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_load_balancer_type(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers (list_load_balancers)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_load_balancers(None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers (create_load_balancer)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .create_load_balancer(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers/actions (list_load_balancers_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_load_balancers_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers/actions/{id} (get_load_balancers_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_load_balancers_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers/{id} (get_load_balancer)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_load_balancer(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // PUT /load_balancers/{id} (update_load_balancer)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/load_balancers/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_load_balancer(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // DELETE /load_balancers/{id} (delete_load_balancer)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/load_balancers/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_load_balancer(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers/{id}/actions (list_load_balancer_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_load_balancer_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/add_service (add_load_balancer_service)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/add_service")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .add_load_balancer_service(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/add_target (add_load_balancer_target)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/add_target")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .add_load_balancer_target(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/attach_to_network (attach_load_balancer_to_network)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/attach_to_network")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .attach_load_balancer_to_network(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/change_algorithm (change_load_balancer_algorithm)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/change_algorithm")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_load_balancer_algorithm(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/change_dns_ptr (change_load_balancer_dns_ptr)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/change_dns_ptr")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_load_balancer_dns_ptr(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/change_protection (change_load_balancer_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_load_balancer_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/change_type (change_load_balancer_type)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/change_type")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_load_balancer_type(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/delete_service (delete_load_balancer_service)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/delete_service")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_load_balancer_service(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/detach_from_network (detach_load_balancer_from_network)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/detach_from_network")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .detach_load_balancer_from_network(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/disable_public_interface (disable_load_balancer_public_interface)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/disable_public_interface")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .disable_load_balancer_public_interface(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/enable_public_interface (enable_load_balancer_public_interface)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/enable_public_interface")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .enable_load_balancer_public_interface(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/remove_target (remove_load_balancer_target)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/remove_target")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .remove_load_balancer_target(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /load_balancers/{id}/actions/update_service (update_load_balancer_service)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/load_balancers/1/actions/update_service")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_load_balancer_service(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers/{id}/actions/{action_id} (get_load_balancer_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_load_balancer_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /load_balancers/{id}/metrics (get_load_balancer_metrics)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/load_balancers/1/metrics")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_load_balancer_metrics(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /locations (list_locations)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/locations")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_locations(None, None).await.unwrap();
    mock.assert();

    // GET /locations/{id} (get_location)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/locations/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_location(1, None, None).await.unwrap();
    mock.assert();

    // GET /networks (list_networks)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/networks")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_networks(None, None).await.unwrap();
    mock.assert();

    // POST /networks (create_network)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_network(None, None).await.unwrap();
    mock.assert();

    // GET /networks/actions (list_networks_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/networks/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_networks_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /networks/actions/{id} (get_networks_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/networks/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_networks_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /networks/{id} (get_network)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/networks/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_network(1, None, None).await.unwrap();
    mock.assert();

    // PUT /networks/{id} (update_network)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/networks/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_network(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /networks/{id} (delete_network)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/networks/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_network(1, None, None).await.unwrap();
    mock.assert();

    // GET /networks/{id}/actions (list_network_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/networks/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_network_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /networks/{id}/actions/add_route (add_network_route)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks/1/actions/add_route")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .add_network_route(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /networks/{id}/actions/add_subnet (add_network_subnet)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks/1/actions/add_subnet")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .add_network_subnet(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /networks/{id}/actions/change_ip_range (change_network_ip_range)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks/1/actions/change_ip_range")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_network_ip_range(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /networks/{id}/actions/change_protection (change_network_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_network_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /networks/{id}/actions/delete_route (delete_network_route)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks/1/actions/delete_route")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_network_route(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /networks/{id}/actions/delete_subnet (delete_network_subnet)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/networks/1/actions/delete_subnet")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_network_subnet(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /networks/{id}/actions/{action_id} (get_network_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/networks/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_network_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /placement_groups (list_placement_groups)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/placement_groups")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_placement_groups(None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /placement_groups (create_placement_group)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/placement_groups")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .create_placement_group(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /placement_groups/{id} (get_placement_group)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/placement_groups/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_placement_group(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // PUT /placement_groups/{id} (update_placement_group)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/placement_groups/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_placement_group(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // DELETE /placement_groups/{id} (delete_placement_group)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/placement_groups/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_placement_group(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /pricing (get_pricing)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/pricing")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_pricing(None, None).await.unwrap();
    mock.assert();

    // GET /primary_ips (list_primary_ips)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/primary_ips")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_primary_ips(None, None).await.unwrap();
    mock.assert();

    // POST /primary_ips (create_primary_ip)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/primary_ips")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_primary_ip(None, None).await.unwrap();
    mock.assert();

    // GET /primary_ips/actions (list_primary_ips_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/primary_ips/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_primary_ips_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /primary_ips/actions/{id} (get_primary_ips_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/primary_ips/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_primary_ips_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /primary_ips/{id} (get_primary_ip)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/primary_ips/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_primary_ip(1, None, None).await.unwrap();
    mock.assert();

    // PUT /primary_ips/{id} (update_primary_ip)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/primary_ips/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_primary_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // DELETE /primary_ips/{id} (delete_primary_ip)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/primary_ips/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_primary_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /primary_ips/{id}/actions (list_primary_ip_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/primary_ips/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_primary_ip_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /primary_ips/{id}/actions/assign (assign_primary_ip)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/primary_ips/1/actions/assign")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .assign_primary_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /primary_ips/{id}/actions/change_dns_ptr (change_primary_ip_dns_ptr)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/primary_ips/1/actions/change_dns_ptr")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_primary_ip_dns_ptr(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /primary_ips/{id}/actions/change_protection (change_primary_ip_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/primary_ips/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_primary_ip_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /primary_ips/{id}/actions/unassign (unassign_primary_ip)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/primary_ips/1/actions/unassign")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .unassign_primary_ip(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /primary_ips/{id}/actions/{action_id} (get_primary_ip_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/primary_ips/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_primary_ip_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /server_types (list_server_types)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/server_types")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_server_types(None, None).await.unwrap();
    mock.assert();

    // GET /server_types/{id} (get_server_type)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/server_types/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_server_type(1, None, None).await.unwrap();
    mock.assert();

    // GET /servers (list_servers)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_servers(None, None).await.unwrap();
    mock.assert();

    // POST /servers (create_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_server(None, None).await.unwrap();
    mock.assert();

    // GET /servers/actions (list_servers_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_servers_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /servers/actions/{id} (get_servers_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_servers_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /servers/{id} (get_server)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_server(1, None, None).await.unwrap();
    mock.assert();

    // PUT /servers/{id} (update_server)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/servers/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_server(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /servers/{id} (delete_server)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/servers/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_server(1, None, None).await.unwrap();
    mock.assert();

    // GET /servers/{id}/actions (list_server_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_server_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/add_to_placement_group (add_server_to_placement_group)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/add_to_placement_group")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .add_server_to_placement_group(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/attach_iso (attach_server_iso)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/attach_iso")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .attach_server_iso(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/attach_to_network (attach_server_to_network)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/attach_to_network")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .attach_server_to_network(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/change_alias_ips (change_server_alias_ips)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/change_alias_ips")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_server_alias_ips(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/change_dns_ptr (change_server_dns_ptr)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/change_dns_ptr")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_server_dns_ptr(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/change_protection (change_server_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_server_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/change_type (change_server_type)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/change_type")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_server_type(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/create_image (create_server_image)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/create_image")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .create_server_image(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/detach_from_network (detach_server_from_network)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/detach_from_network")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .detach_server_from_network(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/detach_iso (detach_server_iso)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/detach_iso")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .detach_server_iso(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/disable_backup (disable_server_backup)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/disable_backup")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .disable_server_backup(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/disable_rescue (disable_server_rescue)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/disable_rescue")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .disable_server_rescue(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/enable_backup (enable_server_backup)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/enable_backup")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .enable_server_backup(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/enable_rescue (enable_server_rescue)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/enable_rescue")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .enable_server_rescue(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/poweroff (poweroff_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/poweroff")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().poweroff_server(1, None, None).await.unwrap();
    mock.assert();

    // POST /servers/{id}/actions/poweron (poweron_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/poweron")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().poweron_server(1, None, None).await.unwrap();
    mock.assert();

    // POST /servers/{id}/actions/reboot (reboot_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/reboot")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().reboot_server(1, None, None).await.unwrap();
    mock.assert();

    // POST /servers/{id}/actions/rebuild (rebuild_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/rebuild")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().rebuild_server(1, None, None).await.unwrap();
    mock.assert();

    // POST /servers/{id}/actions/remove_from_placement_group (remove_server_from_placement_group)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/remove_from_placement_group")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .remove_server_from_placement_group(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/request_console (request_server_console)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/request_console")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .request_server_console(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/reset (reset_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/reset")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().reset_server(1, None, None).await.unwrap();
    mock.assert();

    // POST /servers/{id}/actions/reset_password (reset_server_password)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/reset_password")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .reset_server_password(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /servers/{id}/actions/shutdown (shutdown_server)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/servers/1/actions/shutdown")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().shutdown_server(1, None, None).await.unwrap();
    mock.assert();

    // GET /servers/{id}/actions/{action_id} (get_server_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_server_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /servers/{id}/metrics (get_server_metrics)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/servers/1/metrics")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_server_metrics(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /ssh_keys (list_ssh_keys)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/ssh_keys")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_ssh_keys(None, None).await.unwrap();
    mock.assert();

    // POST /ssh_keys (create_ssh_key)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/ssh_keys")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_ssh_key(None, None).await.unwrap();
    mock.assert();

    // GET /ssh_keys/{id} (get_ssh_key)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/ssh_keys/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_ssh_key(1, None, None).await.unwrap();
    mock.assert();

    // PUT /ssh_keys/{id} (update_ssh_key)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/ssh_keys/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_ssh_key(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /ssh_keys/{id} (delete_ssh_key)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/ssh_keys/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_ssh_key(1, None, None).await.unwrap();
    mock.assert();

    // GET /volumes (list_volumes)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/volumes")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_volumes(None, None).await.unwrap();
    mock.assert();

    // POST /volumes (create_volume)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/volumes")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_volume(None, None).await.unwrap();
    mock.assert();

    // GET /volumes/actions (list_volumes_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/volumes/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_volumes_actions(None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /volumes/actions/{id} (get_volumes_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/volumes/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_volumes_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /volumes/{id} (get_volume)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/volumes/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_volume(1, None, None).await.unwrap();
    mock.assert();

    // PUT /volumes/{id} (update_volume)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/volumes/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_volume(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /volumes/{id} (delete_volume)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/volumes/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_volume(1, None, None).await.unwrap();
    mock.assert();

    // GET /volumes/{id}/actions (list_volume_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/volumes/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_volume_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /volumes/{id}/actions/attach (attach_volume)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/volumes/1/actions/attach")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().attach_volume(1, None, None).await.unwrap();
    mock.assert();

    // POST /volumes/{id}/actions/change_protection (change_volume_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/volumes/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_volume_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /volumes/{id}/actions/detach (detach_volume)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/volumes/1/actions/detach")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().detach_volume(1, None, None).await.unwrap();
    mock.assert();

    // POST /volumes/{id}/actions/resize (resize_volume)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/volumes/1/actions/resize")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().resize_volume(1, None, None).await.unwrap();
    mock.assert();

    // GET /volumes/{id}/actions/{action_id} (get_volume_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/volumes/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_volume_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /zones (list_zones)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_zones(None, None).await.unwrap();
    mock.assert();

    // POST /zones (create_zone)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().create_zone(None, None).await.unwrap();
    mock.assert();

    // GET /zones/actions (list_zones_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().list_zones_actions(None, None).await.unwrap();
    mock.assert();

    // GET /zones/actions/{id} (get_zones_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_zones_action(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /zones/{id_or_name} (get_zone)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().get_zone(1, None, None).await.unwrap();
    mock.assert();

    // PUT /zones/{id_or_name} (update_zone)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/zones/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().update_zone(1, None, None).await.unwrap();
    mock.assert();

    // DELETE /zones/{id_or_name} (delete_zone)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/zones/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().delete_zone(1, None, None).await.unwrap();
    mock.assert();

    // GET /zones/{id_or_name}/actions (list_zone_actions)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/1/actions")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_zone_actions(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/actions/change_primary_nameservers (change_zone_primary_nameservers)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/actions/change_primary_nameservers")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_zone_primary_nameservers(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/actions/change_protection (change_zone_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_zone_protection(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/actions/change_ttl (change_zone_ttl)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/actions/change_ttl")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client.cloud().change_zone_ttl(1, None, None).await.unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/actions/import_zonefile (import_zone_zonefile)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/actions/import_zonefile")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .import_zone_zonefile(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /zones/{id_or_name}/actions/{action_id} (get_zone_action)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/1/actions/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_zone_action(1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /zones/{id_or_name}/rrsets (list_zone_rrsets)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/1/rrsets")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .list_zone_rrsets(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets (create_zone_rrset)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .create_zone_rrset(1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /zones/{id_or_name}/rrsets/{rr_name}/{rr_type} (get_zone_rrset)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/1/rrsets/1/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_zone_rrset(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // PUT /zones/{id_or_name}/rrsets/{rr_name}/{rr_type} (update_zone_rrset)
    let mock = server.mock(|when, then| {
        when.method(PUT)
            .path("/zones/1/rrsets/1/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_zone_rrset(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // DELETE /zones/{id_or_name}/rrsets/{rr_name}/{rr_type} (delete_zone_rrset)
    let mock = server.mock(|when, then| {
        when.method(DELETE)
            .path("/zones/1/rrsets/1/1")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .delete_zone_rrset(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/add_records (add_zone_rrset_records)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets/1/1/actions/add_records")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .add_zone_rrset_records(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_protection (change_zone_rrset_protection)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets/1/1/actions/change_protection")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_zone_rrset_protection(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_ttl (change_zone_rrset_ttl)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets/1/1/actions/change_ttl")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .change_zone_rrset_ttl(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/remove_records (remove_zone_rrset_records)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets/1/1/actions/remove_records")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .remove_zone_rrset_records(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/set_records (set_zone_rrset_records)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets/1/1/actions/set_records")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .set_zone_rrset_records(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/update_records (update_zone_rrset_records)
    let mock = server.mock(|when, then| {
        when.method(POST)
            .path("/zones/1/rrsets/1/1/actions/update_records")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .update_zone_rrset_records(1, 1, 1, None, None)
        .await
        .unwrap();
    mock.assert();

    // GET /zones/{id_or_name}/zonefile (get_zone_zonefile)
    let mock = server.mock(|when, then| {
        when.method(GET)
            .path("/zones/1/zonefile")
            .header("authorization", "Bearer test-token");
        then.status(200)
            .header("content-type", "application/json")
            .body("{}");
    });

    let _ = client
        .cloud()
        .get_zone_zonefile(1, None, None)
        .await
        .unwrap();
    mock.assert();
}
