// Auto-generated by mcp/scripts/generate_e2e_tests.mjs
// E2E test for every OpenAPI operation through MCP CLI.

import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cliPath = path.resolve(__dirname, '..', 'src', 'index.js');

function toRenderedPath(pathTemplate, pathParams) {
  let out = pathTemplate;
  for (const name of pathParams) {
    out = out.replace(`{${name}}`, '1');
  }
  return out;
}

function buildCallArgs(op, baseUrl) {
  const args = [cliPath, '--call', op.operationId, '--base-url', baseUrl, '--token', 'test-token'];
  if (op.pathParams.length > 0) {
    const params = {};
    for (const p of op.pathParams) params[p] = 1;
    args.push('--path-params', JSON.stringify(params));
  }
  return args;
}

const operations = [
  {
    "operationId": "add_load_balancer_service",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/add_service",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "add_load_balancer_target",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/add_target",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "add_network_route",
    "method": "POST",
    "pathTemplate": "/networks/{id}/actions/add_route",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "add_network_subnet",
    "method": "POST",
    "pathTemplate": "/networks/{id}/actions/add_subnet",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "add_server_to_placement_group",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/add_to_placement_group",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "add_zone_rrset_records",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/add_records",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "attach_load_balancer_to_network",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/attach_to_network",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "attach_server_iso",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/attach_iso",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "attach_server_to_network",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/attach_to_network",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "attach_volume",
    "method": "POST",
    "pathTemplate": "/volumes/{id}/actions/attach",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_image_protection",
    "method": "POST",
    "pathTemplate": "/images/{id}/actions/change_protection",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_load_balancer_algorithm",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/change_algorithm",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_load_balancer_dns_ptr",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/change_dns_ptr",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_load_balancer_protection",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/change_protection",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_load_balancer_type",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/change_type",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_network_ip_range",
    "method": "POST",
    "pathTemplate": "/networks/{id}/actions/change_ip_range",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_network_protection",
    "method": "POST",
    "pathTemplate": "/networks/{id}/actions/change_protection",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_server_alias_ips",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/change_alias_ips",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_server_dns_ptr",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/change_dns_ptr",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_server_protection",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/change_protection",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_server_type",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/change_type",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_volume_protection",
    "method": "POST",
    "pathTemplate": "/volumes/{id}/actions/change_protection",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "change_zone_primary_nameservers",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/actions/change_primary_nameservers",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "change_zone_protection",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/actions/change_protection",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "change_zone_rrset_protection",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_protection",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "change_zone_rrset_ttl",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_ttl",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "change_zone_ttl",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/actions/change_ttl",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "create_load_balancer",
    "method": "POST",
    "pathTemplate": "/load_balancers",
    "pathParams": []
  },
  {
    "operationId": "create_network",
    "method": "POST",
    "pathTemplate": "/networks",
    "pathParams": []
  },
  {
    "operationId": "create_server",
    "method": "POST",
    "pathTemplate": "/servers",
    "pathParams": []
  },
  {
    "operationId": "create_server_image",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/create_image",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "create_volume",
    "method": "POST",
    "pathTemplate": "/volumes",
    "pathParams": []
  },
  {
    "operationId": "create_zone",
    "method": "POST",
    "pathTemplate": "/zones",
    "pathParams": []
  },
  {
    "operationId": "create_zone_rrset",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "delete_image",
    "method": "DELETE",
    "pathTemplate": "/images/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_load_balancer",
    "method": "DELETE",
    "pathTemplate": "/load_balancers/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_load_balancer_service",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/delete_service",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_network",
    "method": "DELETE",
    "pathTemplate": "/networks/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_network_route",
    "method": "POST",
    "pathTemplate": "/networks/{id}/actions/delete_route",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_network_subnet",
    "method": "POST",
    "pathTemplate": "/networks/{id}/actions/delete_subnet",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_server",
    "method": "DELETE",
    "pathTemplate": "/servers/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_volume",
    "method": "DELETE",
    "pathTemplate": "/volumes/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "delete_zone",
    "method": "DELETE",
    "pathTemplate": "/zones/{id_or_name}",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "delete_zone_rrset",
    "method": "DELETE",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "detach_load_balancer_from_network",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/detach_from_network",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "detach_server_from_network",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/detach_from_network",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "detach_server_iso",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/detach_iso",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "detach_volume",
    "method": "POST",
    "pathTemplate": "/volumes/{id}/actions/detach",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "disable_load_balancer_public_interface",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/disable_public_interface",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "disable_server_backup",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/disable_backup",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "disable_server_rescue",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/disable_rescue",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "enable_load_balancer_public_interface",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/enable_public_interface",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "enable_server_backup",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/enable_backup",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "enable_server_rescue",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/enable_rescue",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_action",
    "method": "GET",
    "pathTemplate": "/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_actions",
    "method": "GET",
    "pathTemplate": "/actions",
    "pathParams": []
  },
  {
    "operationId": "get_image",
    "method": "GET",
    "pathTemplate": "/images/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_image_action",
    "method": "GET",
    "pathTemplate": "/images/{id}/actions/{action_id}",
    "pathParams": [
      "id",
      "action_id"
    ]
  },
  {
    "operationId": "get_images_action",
    "method": "GET",
    "pathTemplate": "/images/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_iso",
    "method": "GET",
    "pathTemplate": "/isos/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_load_balancer",
    "method": "GET",
    "pathTemplate": "/load_balancers/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_load_balancer_action",
    "method": "GET",
    "pathTemplate": "/load_balancers/{id}/actions/{action_id}",
    "pathParams": [
      "id",
      "action_id"
    ]
  },
  {
    "operationId": "get_load_balancer_metrics",
    "method": "GET",
    "pathTemplate": "/load_balancers/{id}/metrics",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_load_balancer_type",
    "method": "GET",
    "pathTemplate": "/load_balancer_types/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_load_balancers_action",
    "method": "GET",
    "pathTemplate": "/load_balancers/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_network",
    "method": "GET",
    "pathTemplate": "/networks/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_network_action",
    "method": "GET",
    "pathTemplate": "/networks/{id}/actions/{action_id}",
    "pathParams": [
      "id",
      "action_id"
    ]
  },
  {
    "operationId": "get_networks_action",
    "method": "GET",
    "pathTemplate": "/networks/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_server",
    "method": "GET",
    "pathTemplate": "/servers/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_server_action",
    "method": "GET",
    "pathTemplate": "/servers/{id}/actions/{action_id}",
    "pathParams": [
      "id",
      "action_id"
    ]
  },
  {
    "operationId": "get_server_metrics",
    "method": "GET",
    "pathTemplate": "/servers/{id}/metrics",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_servers_action",
    "method": "GET",
    "pathTemplate": "/servers/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_volume",
    "method": "GET",
    "pathTemplate": "/volumes/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_volume_action",
    "method": "GET",
    "pathTemplate": "/volumes/{id}/actions/{action_id}",
    "pathParams": [
      "id",
      "action_id"
    ]
  },
  {
    "operationId": "get_volumes_action",
    "method": "GET",
    "pathTemplate": "/volumes/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "get_zone",
    "method": "GET",
    "pathTemplate": "/zones/{id_or_name}",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "get_zone_action",
    "method": "GET",
    "pathTemplate": "/zones/{id_or_name}/actions/{action_id}",
    "pathParams": [
      "id_or_name",
      "action_id"
    ]
  },
  {
    "operationId": "get_zone_rrset",
    "method": "GET",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "get_zone_zonefile",
    "method": "GET",
    "pathTemplate": "/zones/{id_or_name}/zonefile",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "get_zones_action",
    "method": "GET",
    "pathTemplate": "/zones/actions/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "import_zone_zonefile",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/actions/import_zonefile",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "list_image_actions",
    "method": "GET",
    "pathTemplate": "/images/{id}/actions",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "list_images",
    "method": "GET",
    "pathTemplate": "/images",
    "pathParams": []
  },
  {
    "operationId": "list_images_actions",
    "method": "GET",
    "pathTemplate": "/images/actions",
    "pathParams": []
  },
  {
    "operationId": "list_isos",
    "method": "GET",
    "pathTemplate": "/isos",
    "pathParams": []
  },
  {
    "operationId": "list_load_balancer_actions",
    "method": "GET",
    "pathTemplate": "/load_balancers/{id}/actions",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "list_load_balancer_types",
    "method": "GET",
    "pathTemplate": "/load_balancer_types",
    "pathParams": []
  },
  {
    "operationId": "list_load_balancers",
    "method": "GET",
    "pathTemplate": "/load_balancers",
    "pathParams": []
  },
  {
    "operationId": "list_load_balancers_actions",
    "method": "GET",
    "pathTemplate": "/load_balancers/actions",
    "pathParams": []
  },
  {
    "operationId": "list_network_actions",
    "method": "GET",
    "pathTemplate": "/networks/{id}/actions",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "list_networks",
    "method": "GET",
    "pathTemplate": "/networks",
    "pathParams": []
  },
  {
    "operationId": "list_networks_actions",
    "method": "GET",
    "pathTemplate": "/networks/actions",
    "pathParams": []
  },
  {
    "operationId": "list_server_actions",
    "method": "GET",
    "pathTemplate": "/servers/{id}/actions",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "list_servers",
    "method": "GET",
    "pathTemplate": "/servers",
    "pathParams": []
  },
  {
    "operationId": "list_servers_actions",
    "method": "GET",
    "pathTemplate": "/servers/actions",
    "pathParams": []
  },
  {
    "operationId": "list_volume_actions",
    "method": "GET",
    "pathTemplate": "/volumes/{id}/actions",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "list_volumes",
    "method": "GET",
    "pathTemplate": "/volumes",
    "pathParams": []
  },
  {
    "operationId": "list_volumes_actions",
    "method": "GET",
    "pathTemplate": "/volumes/actions",
    "pathParams": []
  },
  {
    "operationId": "list_zone_actions",
    "method": "GET",
    "pathTemplate": "/zones/{id_or_name}/actions",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "list_zone_rrsets",
    "method": "GET",
    "pathTemplate": "/zones/{id_or_name}/rrsets",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "list_zones",
    "method": "GET",
    "pathTemplate": "/zones",
    "pathParams": []
  },
  {
    "operationId": "list_zones_actions",
    "method": "GET",
    "pathTemplate": "/zones/actions",
    "pathParams": []
  },
  {
    "operationId": "poweroff_server",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/poweroff",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "poweron_server",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/poweron",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "reboot_server",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/reboot",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "rebuild_server",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/rebuild",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "remove_load_balancer_target",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/remove_target",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "remove_server_from_placement_group",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/remove_from_placement_group",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "remove_zone_rrset_records",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/remove_records",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "request_server_console",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/request_console",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "reset_server",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/reset",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "reset_server_password",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/reset_password",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "resize_volume",
    "method": "POST",
    "pathTemplate": "/volumes/{id}/actions/resize",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "set_zone_rrset_records",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/set_records",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "shutdown_server",
    "method": "POST",
    "pathTemplate": "/servers/{id}/actions/shutdown",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_image",
    "method": "PUT",
    "pathTemplate": "/images/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_load_balancer",
    "method": "PUT",
    "pathTemplate": "/load_balancers/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_load_balancer_service",
    "method": "POST",
    "pathTemplate": "/load_balancers/{id}/actions/update_service",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_network",
    "method": "PUT",
    "pathTemplate": "/networks/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_server",
    "method": "PUT",
    "pathTemplate": "/servers/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_volume",
    "method": "PUT",
    "pathTemplate": "/volumes/{id}",
    "pathParams": [
      "id"
    ]
  },
  {
    "operationId": "update_zone",
    "method": "PUT",
    "pathTemplate": "/zones/{id_or_name}",
    "pathParams": [
      "id_or_name"
    ]
  },
  {
    "operationId": "update_zone_rrset",
    "method": "PUT",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  },
  {
    "operationId": "update_zone_rrset_records",
    "method": "POST",
    "pathTemplate": "/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/update_records",
    "pathParams": [
      "id_or_name",
      "rr_name",
      "rr_type"
    ]
  }
];

test('E2E: every OpenAPI route via MCP CLI', async () => {
  let expected = null;

  const server = http.createServer((req, res) => {
    try {
      assert.ok(expected, `Received unexpected request: ${req.method} ${req.url}`);
      const url = new URL(req.url, `http://${req.headers.host}`);
      assert.equal(req.method, expected.method, `Method mismatch for ${expected.operationId}`);
      assert.equal(url.pathname, expected.path, `Path mismatch for ${expected.operationId}`);
      assert.equal(req.headers.authorization, 'Bearer test-token', `Auth header mismatch for ${expected.operationId}`);
    } catch (error) {
      res.statusCode = 500;
      res.setHeader('content-type', 'application/json');
      res.end(JSON.stringify({ error: error.message }));
      return;
    }

    res.statusCode = 200;
    res.setHeader('content-type', 'application/json');
    res.end('{}');
  });

  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const addr = server.address();
  const baseUrl = `http://127.0.0.1:${addr.port}`;

  try {
    for (const op of operations) {
      expected = {
        operationId: op.operationId,
        method: op.method,
        path: toRenderedPath(op.pathTemplate, op.pathParams),
      };

      const result = spawnSync(process.execPath, buildCallArgs(op, baseUrl), {
        encoding: 'utf8',
      });

      assert.equal(result.status, 0, `CLI exited with code ${result.status} for ${op.operationId}. stderr=${result.stderr}`);
      const parsed = JSON.parse(result.stdout);
      assert.equal(parsed.ok, true, `CLI reported failure for ${op.operationId}: ${result.stdout}`);
      assert.equal(parsed.result.ok, true, `HTTP result not ok for ${op.operationId}`);
      assert.equal(parsed.result.method, op.method, `Method result mismatch for ${op.operationId}`);
    }
  } finally {
    server.close();
  }
});
