import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..', '..');

const specPath = process.argv[2] || path.join(root, 'openapi.json');
const outPath = process.argv[3] || path.join(__dirname, '..', 'tests', 'e2e-all-routes.test.mjs');

const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const methods = ['get', 'post', 'put', 'patch', 'delete'];

function opFrom(pathKey, method, item) {
  const op = item?.[method];
  if (!op) return null;
  return {
    operationId: op.operationId || `${method}_${pathKey.replace(/[{}\\/]/g, '_')}`,
    method: method.toUpperCase(),
    pathTemplate: pathKey,
    pathParams: [...pathKey.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]),
  };
}

const ops = [];
for (const [pathKey, item] of Object.entries(spec.paths || {})) {
  for (const method of methods) {
    const op = opFrom(pathKey, method, item);
    if (op) ops.push(op);
  }
}
ops.sort((a, b) => a.operationId.localeCompare(b.operationId));

const lines = [];
lines.push('// Auto-generated by mcp/scripts/generate_e2e_tests.mjs');
lines.push('// E2E test for every OpenAPI operation through MCP CLI.');
lines.push('');
lines.push("import test from 'node:test';");
lines.push("import assert from 'node:assert/strict';");
lines.push("import http from 'node:http';");
lines.push("import { spawnSync } from 'node:child_process';");
lines.push("import path from 'node:path';");
lines.push("import { fileURLToPath } from 'node:url';");
lines.push('');
lines.push('const __filename = fileURLToPath(import.meta.url);');
lines.push('const __dirname = path.dirname(__filename);');
lines.push("const cliPath = path.resolve(__dirname, '..', 'src', 'index.js');");
lines.push('');
lines.push('function toRenderedPath(pathTemplate, pathParams) {');
lines.push("  let out = pathTemplate;");
lines.push('  for (const name of pathParams) {');
lines.push("    out = out.replace(`{${name}}`, '1');");
lines.push('  }');
lines.push('  return out;');
lines.push('}');
lines.push('');
lines.push('function buildCallArgs(op, baseUrl) {');
lines.push("  const args = [cliPath, '--call', op.operationId, '--base-url', baseUrl, '--token', 'test-token'];");
lines.push('  if (op.pathParams.length > 0) {');
lines.push('    const params = {};');
lines.push('    for (const p of op.pathParams) params[p] = 1;');
lines.push("    args.push('--path-params', JSON.stringify(params));");
lines.push('  }');
lines.push('  return args;');
lines.push('}');
lines.push('');
lines.push('const operations = ' + JSON.stringify(ops, null, 2) + ';');
lines.push('');
lines.push("test('E2E: every OpenAPI route via MCP CLI', async () => {");
lines.push('  let expected = null;');
lines.push('');
lines.push('  const server = http.createServer((req, res) => {');
lines.push('    try {');
lines.push('      assert.ok(expected, `Received unexpected request: ${req.method} ${req.url}`);');
lines.push('      const url = new URL(req.url, `http://${req.headers.host}`);');
lines.push('      assert.equal(req.method, expected.method, `Method mismatch for ${expected.operationId}`);');
lines.push('      assert.equal(url.pathname, expected.path, `Path mismatch for ${expected.operationId}`);');
lines.push("      assert.equal(req.headers.authorization, 'Bearer test-token', `Auth header mismatch for ${expected.operationId}`);");
lines.push('    } catch (error) {');
lines.push('      res.statusCode = 500;');
lines.push("      res.setHeader('content-type', 'application/json');");
lines.push('      res.end(JSON.stringify({ error: error.message }));');
lines.push('      return;');
lines.push('    }');
lines.push('');
lines.push('    res.statusCode = 200;');
lines.push("    res.setHeader('content-type', 'application/json');");
lines.push("    res.end('{}');");
lines.push('  });');
lines.push('');
lines.push('  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));');
lines.push('  const addr = server.address();');
lines.push('  const baseUrl = `http://127.0.0.1:${addr.port}`;');
lines.push('');
lines.push('  try {');
lines.push('    for (const op of operations) {');
lines.push('      expected = {');
lines.push('        operationId: op.operationId,');
lines.push('        method: op.method,');
lines.push('        path: toRenderedPath(op.pathTemplate, op.pathParams),');
lines.push('      };');
lines.push('');
lines.push('      const result = spawnSync(process.execPath, buildCallArgs(op, baseUrl), {');
lines.push("        encoding: 'utf8',");
lines.push('      });');
lines.push('');
lines.push("      assert.equal(result.status, 0, `CLI exited with code ${result.status} for ${op.operationId}. stderr=${result.stderr}`);");
lines.push('      const parsed = JSON.parse(result.stdout);');
lines.push('      assert.equal(parsed.ok, true, `CLI reported failure for ${op.operationId}: ${result.stdout}`);');
lines.push('      assert.equal(parsed.result.ok, true, `HTTP result not ok for ${op.operationId}`);');
lines.push('      assert.equal(parsed.result.method, op.method, `Method result mismatch for ${op.operationId}`);');
lines.push('    }');
lines.push('  } finally {');
lines.push('    server.close();');
lines.push('  }');
lines.push('});');
lines.push('');

writeFileSync(outPath, lines.join('\n'));
console.log(`Generated ${outPath} with ${ops.length} operations`);
