#!/usr/bin/env node
/**
 * Generates integration tests for all Hetzner Cloud API operations.
 * Each operation gets its own #[tokio::test]. Tests hit the real API when
 * HETZNER_CLOUD_API_TOKEN is set.
 *
 * Usage: node scripts/generate_cloud_integration_tests.mjs [specPath] [outPath]
 */

import { readFileSync, writeFileSync } from 'node:fs';

const specPath = process.argv[2] ?? 'hetzner-cloud-openapi.json';
const outPath = process.argv[3] ?? 'tests/cloud_integration_test.rs';

const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const paths = spec.paths ?? {};
const methods = ['get', 'post', 'put', 'patch', 'delete'];

// Operations that return 410 deprecated or require special handling - skip
const SKIP_OPERATIONS = new Set([
  'get_actions', // 410 deprecated - requires id query, list endpoint removed
]);

const rustKeywords = new Set([
  'as','break','const','continue','crate','else','enum','extern','false','fn','for','if','impl','in',
  'let','loop','match','mod','move','mut','pub','ref','return','self','Self','static','struct','super',
  'trait','true','type','unsafe','use','where','while','async','await','dyn','abstract','become','box',
  'do','final','macro','override','priv','typeof','unsized','virtual','yield','try'
]);

function sanitizeName(name) {
  let n = (name || '').replace(/[^a-zA-Z0-9_]/g, '_');
  if (!n) n = 'operation';
  if (/^[0-9]/.test(n)) n = `op_${n}`;
  n = n.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
  if (rustKeywords.has(n)) n = `${n}_op`;
  return n;
}

function extractPathParams(pathTemplate, operation, pathItem) {
  const pathParamNames = [...pathTemplate.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
  const opParams = [...(pathItem?.parameters || []), ...(operation.parameters || [])];
  const declaredPath = opParams
    .filter((p) => p.in === 'path' && p.name)
    .map((p) => p.name);
  return [...new Set([...pathParamNames, ...declaredPath])];
}

function placeholderForParam(paramName, path) {
  const name = (paramName || '').toLowerCase();
  // Location/datacenter IDs are strings like "fsn1", "nbg1"
  if (path.includes('/locations/') && name === 'id') return '"fsn1"';
  if (path.includes('/datacenters/') && name === 'id') return '"fsn1-dc3"';
  if (path.includes('/server_types/') && name === 'id') return '"cpx22"';
  if (path.includes('/load_balancer_types/') && name === 'id') return '"lb11"';
  // Zones use id_or_name - string
  if (path.includes('/zones/') && (name === 'id_or_name' || name === 'id')) return '"1"';
  // rr_name, rr_type for zone rrsets
  if (name === 'rr_name') return '"@"';
  if (name === 'rr_type') return '"A"';
  // Default: numeric id
  return '1';
}

const lines = [];
lines.push('//! Integration tests against the real Hetzner Cloud API.');
lines.push('//! Set HETZNER_CLOUD_API_TOKEN to run these tests.');
lines.push('//!');
lines.push('//! Auto-generated by scripts/generate_cloud_integration_tests.mjs');
lines.push('');
lines.push('use hetzner::HetznerClient;');
lines.push('use std::env;');
lines.push('');
lines.push('fn api_token() -> Option<String> {');
lines.push('    dotenv::dotenv().ok();');
lines.push('    dotenv::from_filename(".env.local").ok();');
lines.push('    env::var("HETZNER_CLOUD_API_TOKEN").ok()');
lines.push('}');
lines.push('');

let count = 0;
for (const path of Object.keys(paths).sort()) {
  const pathItem = paths[path];
  for (const verb of methods) {
    const operation = pathItem?.[verb];
    if (!operation) continue;

    const operationId = operation.operationId || `${verb}_${path.replace(/[{}\/]/g, '_')}`;
    if (SKIP_OPERATIONS.has(operationId)) continue;

    const fnName = sanitizeName(operationId);
    const pathParams = extractPathParams(path, operation, pathItem);

    const testName = `test_${fnName}`;
    const placeholders = pathParams.map((p) => placeholderForParam(p, path));
    const argsList = [...placeholders, 'None', 'None'];
    const callArgs = argsList.join(', ');

    lines.push(`#[tokio::test]`);
    lines.push(`async fn ${testName}() {`);
    lines.push(`    let token = match api_token() {`);
    lines.push(`        Some(t) => t,`);
    lines.push(`        None => return,`);
    lines.push(`    };`);
    lines.push(`    let client = HetznerClient::new(token);`);
    lines.push(`    let result = client.cloud().${fnName}(${callArgs}).await;`);
    const isWrite = ['post', 'put', 'patch', 'delete'].includes(verb);
    // Accept: Ok, 404 (not found), invalid_input (missing params), json_error (write ops need body), service_error (API hiccup)
    const acceptCond = isWrite
      ? 'api_err.code == "not_found" || api_err.code == "invalid_input" || api_err.code == "json_error" || api_err.code == "service_error"'
      : 'api_err.code == "not_found" || api_err.code == "invalid_input" || api_err.code == "service_error"';
    lines.push(`    if let Err(e) = &result {`);
    lines.push(`        if let hetzner::HetznerError::Api(api_err) = e {`);
    lines.push(`            if ${acceptCond} { return; }`);
    lines.push(`        }`);
    lines.push(`    }`);
    lines.push('    assert!(result.is_ok(), "' + operationId + ': {:?}", result.err());');
    lines.push(`}`);
    lines.push('');
    count++;
  }
}

writeFileSync(outPath, lines.join('\n'));
console.log(`Generated ${outPath} with ${count} integration tests`);
