import { readFileSync, writeFileSync } from 'node:fs';

const specPath = process.argv[2] ?? 'hetzner-cloud-openapi.json';
const outPath = process.argv[3] ?? 'src/api/cloud/generated_ops.rs';

const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const paths = spec.paths ?? {};

const methods = ['get', 'post', 'put', 'patch', 'delete'];

const rustKeywords = new Set([
  'as','break','const','continue','crate','else','enum','extern','false','fn','for','if','impl','in',
  'let','loop','match','mod','move','mut','pub','ref','return','self','Self','static','struct','super',
  'trait','true','type','unsafe','use','where','while','async','await','dyn','abstract','become','box',
  'do','final','macro','override','priv','typeof','unsized','virtual','yield','try'
]);

function sanitizeName(name) {
  let n = (name || '').replace(/[^a-zA-Z0-9_]/g, '_');
  if (!n) n = 'operation';
  if (/^[0-9]/.test(n)) n = `op_${n}`;
  n = n.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
  if (rustKeywords.has(n)) n = `${n}_op`;
  return n;
}

function rustMethodFor(verb) {
  switch (verb) {
    case 'get': return 'Method::GET';
    case 'post': return 'Method::POST';
    case 'put': return 'Method::PUT';
    case 'patch': return 'Method::PATCH';
    case 'delete': return 'Method::DELETE';
    default: throw new Error(`unsupported method ${verb}`);
  }
}

function extractPathParams(pathTemplate, operation, pathItem) {
  const pathParamNames = [...pathTemplate.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
  const opParams = [...(pathItem?.parameters || []), ...(operation.parameters || [])];
  const declaredPath = opParams
    .filter((p) => p.in === 'path' && p.name)
    .map((p) => p.name);

  const merged = [...new Set([...pathParamNames, ...declaredPath])];
  return merged;
}

const lines = [];
lines.push('// This file is auto-generated by scripts/generate_cloud_ops.mjs.');
lines.push('// Do not edit manually.');
lines.push('');
lines.push('use crate::api::cloud::CloudApi;');
lines.push('use crate::error::Result;');
lines.push('use reqwest::Method;');
lines.push('use serde_json::Value;');
lines.push('');
lines.push("pub type QueryPairs = Vec<(String, String)>;");
lines.push('');
lines.push("impl<'a> CloudApi<'a> {");

for (const path of Object.keys(paths).sort()) {
  const pathItem = paths[path];
  for (const verb of methods) {
    const operation = pathItem?.[verb];
    if (!operation) continue;

    const operationId = operation.operationId || `${verb}_${path.replace(/[{}\/]/g, '_')}`;
    const fnName = sanitizeName(operationId);
    const summary = (operation.summary || '').replace(/\r?\n/g, ' ').trim();

    const pathParams = extractPathParams(path, operation, pathItem);
    const fnArgs = [];
    for (const p of pathParams) {
      fnArgs.push(`${sanitizeName(p)}: impl ToString`);
    }
    fnArgs.push('query: Option<&QueryPairs>');
    fnArgs.push('body: Option<Value>');

    const formatTemplate = path.replace(/\{[^}]+\}/g, '{}');
    const formatArgs = pathParams.map((p) => `${sanitizeName(p)}.to_string()`).join(', ');
    const pathExpr = pathParams.length === 0
      ? `let path = \"${path.replace(/^\//, '')}\".to_string();`
      : `let path = format!(\"${formatTemplate.replace(/^\//, '')}\", ${formatArgs});`;

    lines.push('    /// Auto-generated from Hetzner Cloud OpenAPI.');
    if (summary) lines.push(`    /// ${summary}`);
    lines.push(`    /// ${verb.toUpperCase()} ${path}`);
    lines.push(`    pub async fn ${fnName}(self, ${fnArgs.join(', ')}) -> Result<Value> {`);
    lines.push(`        ${pathExpr}`);
    lines.push(
      `        self.client.request_cloud(${rustMethodFor(verb)}, &path, query, body).await`
    );
    lines.push('    }');
    lines.push('');
  }
}

lines.push('}');
lines.push('');

writeFileSync(outPath, lines.join('\n'));
console.log(`Generated ${outPath}`);
