import { readFileSync, writeFileSync } from 'node:fs';

const specPath = process.argv[2] ?? 'hetzner-cloud-openapi.json';
const outPath = process.argv[3] ?? 'tests/cloud_generated_ops_full_test.rs';

const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const paths = spec.paths ?? {};
const methods = ['get', 'post', 'put', 'patch', 'delete'];

const rustKeywords = new Set([
  'as','break','const','continue','crate','else','enum','extern','false','fn','for','if','impl','in',
  'let','loop','match','mod','move','mut','pub','ref','return','self','Self','static','struct','super',
  'trait','true','type','unsafe','use','where','while','async','await','dyn','abstract','become','box',
  'do','final','macro','override','priv','typeof','unsized','virtual','yield','try'
]);

function sanitizeName(name) {
  let n = (name || '').replace(/[^a-zA-Z0-9_]/g, '_');
  if (!n) n = 'operation';
  if (/^[0-9]/.test(n)) n = `op_${n}`;
  n = n.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
  if (rustKeywords.has(n)) n = `${n}_op`;
  return n;
}

function extractPathParams(pathTemplate, operation, pathItem) {
  const pathParamNames = [...pathTemplate.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
  const opParams = [...(pathItem?.parameters || []), ...(operation.parameters || [])];
  const declaredPath = opParams
    .filter((p) => p.in === 'path' && p.name)
    .map((p) => p.name);

  return [...new Set([...pathParamNames, ...declaredPath])];
}

const lines = [];
lines.push('// This file is auto-generated by scripts/generate_cloud_ops_tests.mjs.');
lines.push('// Do not edit manually.');
lines.push('');
lines.push('use hetzner::HetznerClient;');
lines.push('use httpmock::prelude::*;');
lines.push('');
lines.push('#[tokio::test]');
lines.push('async fn test_all_generated_cloud_openapi_operations() {');
lines.push('    let server = MockServer::start();');
lines.push('    let client = HetznerClient::new("test-token").with_cloud_base_url(server.base_url());');
lines.push('');

for (const path of Object.keys(paths).sort()) {
  const pathItem = paths[path];
  for (const verb of methods) {
    const operation = pathItem?.[verb];
    if (!operation) continue;

    const operationId = operation.operationId || `${verb}_${path.replace(/[{}\/]/g, '_')}`;
    const fnName = sanitizeName(operationId);
    const methodConst = verb.toUpperCase();

    const pathParams = extractPathParams(path, operation, pathItem);
    let requestPath = path;
    for (const _p of pathParams) {
      requestPath = requestPath.replace(/\{[^}]+\}/, '1');
    }

    const args = pathParams.map(() => '1').join(', ');
    const callPrefix = args.length > 0 ? `${args}, ` : '';

    lines.push(`    // ${methodConst} ${path} (${operationId})`);
    lines.push('    let mock = server.mock(|when, then| {');
    lines.push(`        when.method(${methodConst})`);
    lines.push(`            .path("${requestPath}")`);
    lines.push('            .header("authorization", "Bearer test-token");');
    lines.push('        then.status(200)');
    lines.push('            .header("content-type", "application/json")');
    lines.push('            .body("{}");');
    lines.push('    });');
    lines.push('');
    lines.push(`    let _ = client.cloud().${fnName}(${callPrefix}None, None).await.unwrap();`);
    lines.push('    mock.assert();');
    lines.push('');
  }
}

lines.push('}');
lines.push('');

writeFileSync(outPath, lines.join('\n'));
console.log(`Generated ${outPath}`);
