// This file is auto-generated by scripts/generate_cloud_ops.mjs.
// Do not edit manually.

use crate::api::cloud::CloudApi;
use crate::error::Result;
use reqwest::Method;
use serde_json::Value;

pub type QueryPairs = Vec<(String, String)>;

impl<'a> CloudApi<'a> {
    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get multiple Actions
    /// GET /actions
    pub async fn get_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /actions/{id}
    pub async fn get_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Certificates
    /// GET /certificates
    pub async fn list_certificates(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "certificates".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Certificate
    /// POST /certificates
    pub async fn create_certificate(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "certificates".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /certificates/actions
    pub async fn list_certificates_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "certificates/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /certificates/actions/{id}
    pub async fn get_certificates_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("certificates/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Certificate
    /// GET /certificates/{id}
    pub async fn get_certificate(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("certificates/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Certificate
    /// PUT /certificates/{id}
    pub async fn update_certificate(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("certificates/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Certificate
    /// DELETE /certificates/{id}
    pub async fn delete_certificate(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("certificates/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Certificate
    /// GET /certificates/{id}/actions
    pub async fn list_certificate_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("certificates/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Retry Issuance or Renewal
    /// POST /certificates/{id}/actions/retry
    pub async fn retry_certificate(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("certificates/{}/actions/retry", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Certificate
    /// GET /certificates/{id}/actions/{action_id}
    pub async fn get_certificate_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "certificates/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Data Centers
    /// GET /datacenters
    pub async fn list_datacenters(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "datacenters".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Data Center
    /// GET /datacenters/{id}
    pub async fn get_datacenter(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("datacenters/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Firewalls
    /// GET /firewalls
    pub async fn list_firewalls(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "firewalls".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Firewall
    /// POST /firewalls
    pub async fn create_firewall(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "firewalls".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /firewalls/actions
    pub async fn list_firewalls_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "firewalls/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /firewalls/actions/{id}
    pub async fn get_firewalls_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Firewall
    /// GET /firewalls/{id}
    pub async fn get_firewall(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Firewall
    /// PUT /firewalls/{id}
    pub async fn update_firewall(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Firewall
    /// DELETE /firewalls/{id}
    pub async fn delete_firewall(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Firewall
    /// GET /firewalls/{id}/actions
    pub async fn list_firewall_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Apply to Resources
    /// POST /firewalls/{id}/actions/apply_to_resources
    pub async fn apply_firewall_to_resources(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}/actions/apply_to_resources", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Remove from Resources
    /// POST /firewalls/{id}/actions/remove_from_resources
    pub async fn remove_firewall_from_resources(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}/actions/remove_from_resources", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Set Rules
    /// POST /firewalls/{id}/actions/set_rules
    pub async fn set_firewall_rules(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("firewalls/{}/actions/set_rules", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Firewall
    /// GET /firewalls/{id}/actions/{action_id}
    pub async fn get_firewall_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "firewalls/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Floating IPs
    /// GET /floating_ips
    pub async fn list_floating_ips(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "floating_ips".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Floating IP
    /// POST /floating_ips
    pub async fn create_floating_ip(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "floating_ips".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /floating_ips/actions
    pub async fn list_floating_ips_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "floating_ips/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /floating_ips/actions/{id}
    pub async fn get_floating_ips_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Floating IP
    /// GET /floating_ips/{id}
    pub async fn get_floating_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Floating IP
    /// PUT /floating_ips/{id}
    pub async fn update_floating_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Floating IP
    /// DELETE /floating_ips/{id}
    pub async fn delete_floating_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Floating IP
    /// GET /floating_ips/{id}/actions
    pub async fn list_floating_ip_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Assign a Floating IP to a Server
    /// POST /floating_ips/{id}/actions/assign
    pub async fn assign_floating_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}/actions/assign", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change reverse DNS records for a Floating IP
    /// POST /floating_ips/{id}/actions/change_dns_ptr
    pub async fn change_floating_ip_dns_ptr(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}/actions/change_dns_ptr", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Floating IP Protection
    /// POST /floating_ips/{id}/actions/change_protection
    pub async fn change_floating_ip_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}/actions/change_protection", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Unassign a Floating IP
    /// POST /floating_ips/{id}/actions/unassign
    pub async fn unassign_floating_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("floating_ips/{}/actions/unassign", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Floating IP
    /// GET /floating_ips/{id}/actions/{action_id}
    pub async fn get_floating_ip_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "floating_ips/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Images
    /// GET /images
    pub async fn list_images(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "images".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /images/actions
    pub async fn list_images_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "images/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /images/actions/{id}
    pub async fn get_images_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("images/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Image
    /// GET /images/{id}
    pub async fn get_image(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("images/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update an Image
    /// PUT /images/{id}
    pub async fn update_image(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("images/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete an Image
    /// DELETE /images/{id}
    pub async fn delete_image(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("images/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for an Image
    /// GET /images/{id}/actions
    pub async fn list_image_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("images/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Image Protection
    /// POST /images/{id}/actions/change_protection
    pub async fn change_image_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("images/{}/actions/change_protection", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for an Image
    /// GET /images/{id}/actions/{action_id}
    pub async fn get_image_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "images/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List ISOs
    /// GET /isos
    pub async fn list_isos(self, query: Option<&QueryPairs>, body: Option<Value>) -> Result<Value> {
        let path = "isos".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an ISO
    /// GET /isos/{id}
    pub async fn get_iso(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("isos/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Load Balancer Types
    /// GET /load_balancer_types
    pub async fn list_load_balancer_types(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "load_balancer_types".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Load Balancer Type
    /// GET /load_balancer_types/{id}
    pub async fn get_load_balancer_type(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancer_types/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Load Balancers
    /// GET /load_balancers
    pub async fn list_load_balancers(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "load_balancers".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Load Balancer
    /// POST /load_balancers
    pub async fn create_load_balancer(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "load_balancers".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /load_balancers/actions
    pub async fn list_load_balancers_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "load_balancers/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /load_balancers/actions/{id}
    pub async fn get_load_balancers_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Load Balancer
    /// GET /load_balancers/{id}
    pub async fn get_load_balancer(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Load Balancer
    /// PUT /load_balancers/{id}
    pub async fn update_load_balancer(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Load Balancer
    /// DELETE /load_balancers/{id}
    pub async fn delete_load_balancer(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Load Balancer
    /// GET /load_balancers/{id}/actions
    pub async fn list_load_balancer_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Add Service
    /// POST /load_balancers/{id}/actions/add_service
    pub async fn add_load_balancer_service(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/add_service", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Add Target
    /// POST /load_balancers/{id}/actions/add_target
    pub async fn add_load_balancer_target(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/add_target", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Attach a Load Balancer to a Network
    /// POST /load_balancers/{id}/actions/attach_to_network
    pub async fn attach_load_balancer_to_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "load_balancers/{}/actions/attach_to_network",
            id.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Algorithm
    /// POST /load_balancers/{id}/actions/change_algorithm
    pub async fn change_load_balancer_algorithm(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/change_algorithm", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change reverse DNS entry for this Load Balancer
    /// POST /load_balancers/{id}/actions/change_dns_ptr
    pub async fn change_load_balancer_dns_ptr(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/change_dns_ptr", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Load Balancer Protection
    /// POST /load_balancers/{id}/actions/change_protection
    pub async fn change_load_balancer_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "load_balancers/{}/actions/change_protection",
            id.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change the Type of a Load Balancer
    /// POST /load_balancers/{id}/actions/change_type
    pub async fn change_load_balancer_type(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/change_type", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete Service
    /// POST /load_balancers/{id}/actions/delete_service
    pub async fn delete_load_balancer_service(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/delete_service", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Detach a Load Balancer from a Network
    /// POST /load_balancers/{id}/actions/detach_from_network
    pub async fn detach_load_balancer_from_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "load_balancers/{}/actions/detach_from_network",
            id.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Disable the public interface of a Load Balancer
    /// POST /load_balancers/{id}/actions/disable_public_interface
    pub async fn disable_load_balancer_public_interface(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "load_balancers/{}/actions/disable_public_interface",
            id.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Enable the public interface of a Load Balancer
    /// POST /load_balancers/{id}/actions/enable_public_interface
    pub async fn enable_load_balancer_public_interface(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "load_balancers/{}/actions/enable_public_interface",
            id.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Remove Target
    /// POST /load_balancers/{id}/actions/remove_target
    pub async fn remove_load_balancer_target(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/remove_target", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update Service
    /// POST /load_balancers/{id}/actions/update_service
    pub async fn update_load_balancer_service(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/actions/update_service", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Load Balancer
    /// GET /load_balancers/{id}/actions/{action_id}
    pub async fn get_load_balancer_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "load_balancers/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get Metrics for a LoadBalancer
    /// GET /load_balancers/{id}/metrics
    pub async fn get_load_balancer_metrics(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("load_balancers/{}/metrics", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Locations
    /// GET /locations
    pub async fn list_locations(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "locations".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Location
    /// GET /locations/{id}
    pub async fn get_location(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("locations/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Networks
    /// GET /networks
    pub async fn list_networks(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "networks".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Network
    /// POST /networks
    pub async fn create_network(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "networks".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /networks/actions
    pub async fn list_networks_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "networks/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /networks/actions/{id}
    pub async fn get_networks_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Network
    /// GET /networks/{id}
    pub async fn get_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Network
    /// PUT /networks/{id}
    pub async fn update_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Network
    /// DELETE /networks/{id}
    pub async fn delete_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Network
    /// GET /networks/{id}/actions
    pub async fn list_network_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Add a route to a Network
    /// POST /networks/{id}/actions/add_route
    pub async fn add_network_route(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions/add_route", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Add a subnet to a Network
    /// POST /networks/{id}/actions/add_subnet
    pub async fn add_network_subnet(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions/add_subnet", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change IP range of a Network
    /// POST /networks/{id}/actions/change_ip_range
    pub async fn change_network_ip_range(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions/change_ip_range", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Network Protection
    /// POST /networks/{id}/actions/change_protection
    pub async fn change_network_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions/change_protection", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a route from a Network
    /// POST /networks/{id}/actions/delete_route
    pub async fn delete_network_route(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions/delete_route", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a subnet from a Network
    /// POST /networks/{id}/actions/delete_subnet
    pub async fn delete_network_subnet(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("networks/{}/actions/delete_subnet", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Network
    /// GET /networks/{id}/actions/{action_id}
    pub async fn get_network_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "networks/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Placement Groups
    /// GET /placement_groups
    pub async fn list_placement_groups(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "placement_groups".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a PlacementGroup
    /// POST /placement_groups
    pub async fn create_placement_group(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "placement_groups".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a PlacementGroup
    /// GET /placement_groups/{id}
    pub async fn get_placement_group(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("placement_groups/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a PlacementGroup
    /// PUT /placement_groups/{id}
    pub async fn update_placement_group(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("placement_groups/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a PlacementGroup
    /// DELETE /placement_groups/{id}
    pub async fn delete_placement_group(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("placement_groups/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get all prices
    /// GET /pricing
    pub async fn get_pricing(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "pricing".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Primary IPs
    /// GET /primary_ips
    pub async fn list_primary_ips(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "primary_ips".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Primary IP
    /// POST /primary_ips
    pub async fn create_primary_ip(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "primary_ips".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /primary_ips/actions
    pub async fn list_primary_ips_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "primary_ips/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /primary_ips/actions/{id}
    pub async fn get_primary_ips_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Primary IP
    /// GET /primary_ips/{id}
    pub async fn get_primary_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Primary IP
    /// PUT /primary_ips/{id}
    pub async fn update_primary_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Primary IP
    /// DELETE /primary_ips/{id}
    pub async fn delete_primary_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Primary IP
    /// GET /primary_ips/{id}/actions
    pub async fn list_primary_ip_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Assign a Primary IP to a resource
    /// POST /primary_ips/{id}/actions/assign
    pub async fn assign_primary_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}/actions/assign", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change reverse DNS records for a Primary IP
    /// POST /primary_ips/{id}/actions/change_dns_ptr
    pub async fn change_primary_ip_dns_ptr(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}/actions/change_dns_ptr", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Primary IP Protection
    /// POST /primary_ips/{id}/actions/change_protection
    pub async fn change_primary_ip_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}/actions/change_protection", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Unassign a Primary IP from a resource
    /// POST /primary_ips/{id}/actions/unassign
    pub async fn unassign_primary_ip(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("primary_ips/{}/actions/unassign", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Primary IP
    /// GET /primary_ips/{id}/actions/{action_id}
    pub async fn get_primary_ip_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "primary_ips/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Server Types
    /// GET /server_types
    pub async fn list_server_types(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "server_types".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Server Type
    /// GET /server_types/{id}
    pub async fn get_server_type(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("server_types/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Servers
    /// GET /servers
    pub async fn list_servers(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "servers".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Server
    /// POST /servers
    pub async fn create_server(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "servers".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /servers/actions
    pub async fn list_servers_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "servers/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /servers/actions/{id}
    pub async fn get_servers_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Server
    /// GET /servers/{id}
    pub async fn get_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Server
    /// PUT /servers/{id}
    pub async fn update_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Server
    /// DELETE /servers/{id}
    pub async fn delete_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Server
    /// GET /servers/{id}/actions
    pub async fn list_server_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Add a Server to a Placement Group
    /// POST /servers/{id}/actions/add_to_placement_group
    pub async fn add_server_to_placement_group(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/add_to_placement_group", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Attach an ISO to a Server
    /// POST /servers/{id}/actions/attach_iso
    pub async fn attach_server_iso(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/attach_iso", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Attach a Server to a Network
    /// POST /servers/{id}/actions/attach_to_network
    pub async fn attach_server_to_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/attach_to_network", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change alias IPs of a Network
    /// POST /servers/{id}/actions/change_alias_ips
    pub async fn change_server_alias_ips(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/change_alias_ips", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change reverse DNS entry for this Server
    /// POST /servers/{id}/actions/change_dns_ptr
    pub async fn change_server_dns_ptr(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/change_dns_ptr", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Server Protection
    /// POST /servers/{id}/actions/change_protection
    pub async fn change_server_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/change_protection", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change the Type of a Server
    /// POST /servers/{id}/actions/change_type
    pub async fn change_server_type(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/change_type", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create Image from a Server
    /// POST /servers/{id}/actions/create_image
    pub async fn create_server_image(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/create_image", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Detach a Server from a Network
    /// POST /servers/{id}/actions/detach_from_network
    pub async fn detach_server_from_network(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/detach_from_network", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Detach an ISO from a Server
    /// POST /servers/{id}/actions/detach_iso
    pub async fn detach_server_iso(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/detach_iso", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Disable Backups for a Server
    /// POST /servers/{id}/actions/disable_backup
    pub async fn disable_server_backup(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/disable_backup", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Disable Rescue Mode for a Server
    /// POST /servers/{id}/actions/disable_rescue
    pub async fn disable_server_rescue(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/disable_rescue", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Enable and Configure Backups for a Server
    /// POST /servers/{id}/actions/enable_backup
    pub async fn enable_server_backup(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/enable_backup", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Enable Rescue Mode for a Server
    /// POST /servers/{id}/actions/enable_rescue
    pub async fn enable_server_rescue(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/enable_rescue", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Power off a Server
    /// POST /servers/{id}/actions/poweroff
    pub async fn poweroff_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/poweroff", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Power on a Server
    /// POST /servers/{id}/actions/poweron
    pub async fn poweron_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/poweron", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Soft-reboot a Server
    /// POST /servers/{id}/actions/reboot
    pub async fn reboot_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/reboot", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Rebuild a Server from an Image
    /// POST /servers/{id}/actions/rebuild
    pub async fn rebuild_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/rebuild", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Remove from Placement Group
    /// POST /servers/{id}/actions/remove_from_placement_group
    pub async fn remove_server_from_placement_group(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "servers/{}/actions/remove_from_placement_group",
            id.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Request Console for a Server
    /// POST /servers/{id}/actions/request_console
    pub async fn request_server_console(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/request_console", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Reset a Server
    /// POST /servers/{id}/actions/reset
    pub async fn reset_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/reset", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Reset root Password of a Server
    /// POST /servers/{id}/actions/reset_password
    pub async fn reset_server_password(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/reset_password", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Shutdown a Server
    /// POST /servers/{id}/actions/shutdown
    pub async fn shutdown_server(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/actions/shutdown", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Server
    /// GET /servers/{id}/actions/{action_id}
    pub async fn get_server_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "servers/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get Metrics for a Server
    /// GET /servers/{id}/metrics
    pub async fn get_server_metrics(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("servers/{}/metrics", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List SSH keys
    /// GET /ssh_keys
    pub async fn list_ssh_keys(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "ssh_keys".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create an SSH key
    /// POST /ssh_keys
    pub async fn create_ssh_key(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "ssh_keys".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a SSH key
    /// GET /ssh_keys/{id}
    pub async fn get_ssh_key(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("ssh_keys/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update an SSH key
    /// PUT /ssh_keys/{id}
    pub async fn update_ssh_key(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("ssh_keys/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete an SSH key
    /// DELETE /ssh_keys/{id}
    pub async fn delete_ssh_key(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("ssh_keys/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Volumes
    /// GET /volumes
    pub async fn list_volumes(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "volumes".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Volume
    /// POST /volumes
    pub async fn create_volume(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "volumes".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /volumes/actions
    pub async fn list_volumes_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "volumes/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /volumes/actions/{id}
    pub async fn get_volumes_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Volume
    /// GET /volumes/{id}
    pub async fn get_volume(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Volume
    /// PUT /volumes/{id}
    pub async fn update_volume(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}", id.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Volume
    /// DELETE /volumes/{id}
    pub async fn delete_volume(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}", id.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Volume
    /// GET /volumes/{id}/actions
    pub async fn list_volume_actions(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}/actions", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Attach Volume to a Server
    /// POST /volumes/{id}/actions/attach
    pub async fn attach_volume(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}/actions/attach", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change Volume Protection
    /// POST /volumes/{id}/actions/change_protection
    pub async fn change_volume_protection(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}/actions/change_protection", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Detach Volume
    /// POST /volumes/{id}/actions/detach
    pub async fn detach_volume(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}/actions/detach", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Resize Volume
    /// POST /volumes/{id}/actions/resize
    pub async fn resize_volume(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("volumes/{}/actions/resize", id.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Volume
    /// GET /volumes/{id}/actions/{action_id}
    pub async fn get_volume_action(
        self,
        id: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "volumes/{}/actions/{}",
            id.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Zones
    /// GET /zones
    pub async fn list_zones(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "zones".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create a Zone
    /// POST /zones
    pub async fn create_zone(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "zones".to_string();
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions
    /// GET /zones/actions
    pub async fn list_zones_actions(
        self,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = "zones/actions".to_string();
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action
    /// GET /zones/actions/{id}
    pub async fn get_zones_action(
        self,
        id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/actions/{}", id.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get a Zone
    /// GET /zones/{id_or_name}
    pub async fn get_zone(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}", id_or_name.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update a Zone
    /// PUT /zones/{id_or_name}
    pub async fn update_zone(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}", id_or_name.to_string());
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete a Zone
    /// DELETE /zones/{id_or_name}
    pub async fn delete_zone(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}", id_or_name.to_string());
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List Actions for a Zone
    /// GET /zones/{id_or_name}/actions
    pub async fn list_zone_actions(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/actions", id_or_name.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change a Zone's Primary Nameservers
    /// POST /zones/{id_or_name}/actions/change_primary_nameservers
    pub async fn change_zone_primary_nameservers(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/actions/change_primary_nameservers",
            id_or_name.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change a Zone's Protection
    /// POST /zones/{id_or_name}/actions/change_protection
    pub async fn change_zone_protection(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/actions/change_protection", id_or_name.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change a Zone's Default TTL
    /// POST /zones/{id_or_name}/actions/change_ttl
    pub async fn change_zone_ttl(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/actions/change_ttl", id_or_name.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Import a Zone file
    /// POST /zones/{id_or_name}/actions/import_zonefile
    pub async fn import_zone_zonefile(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/actions/import_zonefile", id_or_name.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an Action for a Zone
    /// GET /zones/{id_or_name}/actions/{action_id}
    pub async fn get_zone_action(
        self,
        id_or_name: impl ToString,
        action_id: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/actions/{}",
            id_or_name.to_string(),
            action_id.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// List RRSets
    /// GET /zones/{id_or_name}/rrsets
    pub async fn list_zone_rrsets(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/rrsets", id_or_name.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Create an RRSet
    /// POST /zones/{id_or_name}/rrsets
    pub async fn create_zone_rrset(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/rrsets", id_or_name.to_string());
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Get an RRSet
    /// GET /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}
    pub async fn get_zone_rrset(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update an RRSet
    /// PUT /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}
    pub async fn update_zone_rrset(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::PUT, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Delete an RRSet
    /// DELETE /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}
    pub async fn delete_zone_rrset(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::DELETE, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Add Records to an RRSet
    /// POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/add_records
    pub async fn add_zone_rrset_records(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}/actions/add_records",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change an RRSet's Protection
    /// POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_protection
    pub async fn change_zone_rrset_protection(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}/actions/change_protection",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Change an RRSet's TTL
    /// POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_ttl
    pub async fn change_zone_rrset_ttl(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}/actions/change_ttl",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Remove Records from an RRSet
    /// POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/remove_records
    pub async fn remove_zone_rrset_records(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}/actions/remove_records",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Set Records of an RRSet
    /// POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/set_records
    pub async fn set_zone_rrset_records(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}/actions/set_records",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Update Records of an RRSet
    /// POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/update_records
    pub async fn update_zone_rrset_records(
        self,
        id_or_name: impl ToString,
        rr_name: impl ToString,
        rr_type: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!(
            "zones/{}/rrsets/{}/{}/actions/update_records",
            id_or_name.to_string(),
            rr_name.to_string(),
            rr_type.to_string()
        );
        self.client
            .request_cloud(Method::POST, &path, query, body)
            .await
    }

    /// Auto-generated from Hetzner Cloud OpenAPI.
    /// Export a Zone file
    /// GET /zones/{id_or_name}/zonefile
    pub async fn get_zone_zonefile(
        self,
        id_or_name: impl ToString,
        query: Option<&QueryPairs>,
        body: Option<Value>,
    ) -> Result<Value> {
        let path = format!("zones/{}/zonefile", id_or_name.to_string());
        self.client
            .request_cloud(Method::GET, &path, query, body)
            .await
    }
}
